name: Deploy to Snapcraft

on:
  workflow_dispatch:

jobs:
  deploy-snap:
    name: Build and Publish Snap
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read Flutter version
        id: flutter-version
        run: echo "version=$(cat .flutter-version)" >> $GITHUB_OUTPUT

      - name: Install Flutter dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev libcurl4-openssl-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.flutter-version.outputs.version }}

      - name: Prepare App
        run: |
          flutter doctor -v
          cp lib/.env.dart.example lib/.env.dart
          echo "const FLUTTER_VERSION = const <String, String>" > lib/flutter_version.dart
          flutter --version --machine >> lib/flutter_version.dart
          echo ";" >> lib/flutter_version.dart
          flutter pub get
          flutter config --enable-linux-desktop
          flutter build linux --release -t lib/main.dart

      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic --channel=7.x/stable
          sudo snap install core22
          sudo snap install gnome-42-2204
          sudo snap install gtk-common-themes

      - name: Build Snap
        env:
          SNAPCRAFT_BUILD_ENVIRONMENT: host
        run: snapcraft pack --output invoiceninja.snap

      - name: Publish to Snap Store
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        run: snapcraft upload invoiceninja.snap --release stable
